spring:
  datasource:
    url: jdbc:mysql://nextpick-db.c1oamgcmgpra.ap-northeast-2.rds.amazonaws.com:13306/nextpick?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: nextpick1004
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
